version: "3"
services:
  redis:
    image: 3dsinteractive/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - './redis_cfg:/opt/bitnami/redis/etc'
  